---
- name: Deploy Apache HTTPD container on Docker
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Create directory for web content
      file:
        path: /opt/apache-html
        state: directory
        mode: '0755'

    - name: Copy index.html to web content directory
      copy:
        src: ../files/index.html
        dest: /opt/apache-html/index.html
        mode: '0644'

    - name: Remove existing Apache HTTPD container (if it exists)
      shell: docker rm -f apache-httpd || true

    - name: Pull latest Apache HTTPD image
      shell: docker pull httpd:latest

    - name: Run Apache HTTPD container
      shell: |
        docker run -d \
          --name apache-httpd \
          -p 8080:80 \
          -v /opt/apache-html:/usr/local/apache2/htdocs/ \
          --restart always \
          httpd:latest

