---
- name: Test web server setup
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Check if Python 3.7 is installed
      raw: python3.7 --version
      register: python_version
      changed_when: false

    - name: Check if Apache2 is installed
      raw: apache2 -v
      register: apache_version
      changed_when: false

    - name: Check if Apache2 service is running
      raw: systemctl is-active apache2
      register: apache_status
      changed_when: false

    - name: Check if index.html exists and has correct permissions
      raw: ls -l /var/www/html/index.html
      register: index_file
      changed_when: false

    - name: Display test results
      debug:
        msg:
          - "Python version: {{ python_version.stdout }}"
          - "Apache version: {{ apache_version.stdout }}"
          - "Apache service status: {{ apache_status.stdout }}"
          - "Index file status: {{ index_file.stdout }}" 